# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build And Push Container ACR
  jobs:
  - job: Build
    displayName: Build and Push
    pool:
      vmImage: $(vmImageName)
    steps:
      - task: DockerCompose@0
        inputs:
          containerregistrytype: 'Azure Container Registry'
          azureSubscription: '$(AZURE_SUBSCRIPTION)'
          azureContainerRegistry: '$(AZURE_CONTAINER_REGISTRY)'
          dockerComposeFile: '$(System.DefaultWorkingDirectory)/docker-compose.yml'
          action: 'Build services'
          includeSourceTags: true
          includeLatestTag: true
      - task: DockerCompose@0
        inputs:
          containerregistrytype: 'Azure Container Registry'
          azureSubscription: '$(AZURE_SUBSCRIPTION)'
          azureContainerRegistry: '$(AZURE_CONTAINER_REGISTRY)'
          dockerComposeFile: '$(System.DefaultWorkingDirectory)/docker-compose.yml'
          action: 'Push services'
          includeSourceTags: true
          includeLatestTag: true
      
      