trigger:
- main

resources:
- repo: self

variables:
  unitTeste: '$(System.DefaultWorkingDirectory)/BlogPetNews.Unit.Tests/BlogPetNews.Unit.Tests.csproj'
  integrationTeste: '$(System.DefaultWorkingDirectory)/BlogPetNews.Integration.Tests/BlogPetNews.Integration.Tests.csproj'
  vmImageName: 'ubuntu-latest'

stages:
- stage: Test
  displayName: 'Test Stage'
  jobs:
  - job: UnitTests
    displayName: 'Run Unit Tests'
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: dotnet test $(unitTeste) --configuration Release
      displayName: 'Run Unit Tests'
  - job: IntegrationTests
    displayName: 'Run Integration Tests'
    pool:
      vmImage: $(vmImageName)
    steps:
    - script: dotnet test $(integrationTeste) --configuration Release
      displayName: 'Run Integration Tests'