version: '3'

services:
    blogpetnews:
        build: ./BlogPetNews.API
        image: rm348780.azurecr.io/techchallenge/blogpetnews
        container_name: blogpetnews
        ports:
            - "8080:80"
        networks:
            - blogpets-network
        depends_on:
            - petnewsdb

    petnewsdb:
        image: postgres
        container_name: blogpetnewsdb
        restart: always
        environment:
            POSTGRES_USER: blogpetnews
            POSTGRES_PASSWORD: "yLDLla@23X!lyDz"
        ports:
            - "5432:5432"
        networks:
            - blogpets-network

networks:
    blogpets-network:
        driver: bridge    

