version: '3'

services:
    petnewsdb:
        image: mcr.microsoft.com/mssql/server:2019-latest
        container_name: blogpetnewsdb
        environment:
            SA_PASSWORD: "rAbt2RVFWDHtA8f"
            ACCEPT_EULA: "Y"
            MSSQL_PID: "Developer"
        ports:
            - "1433:1433"
        networks:
            - blogpets-network

    blogpetnews:
        build: ./BlogPetNews.API
        image: rm348780acr.azurecr.io/techchallenge/blogpetnews
        container_name: blogpetnews
        environment:
            ConnectionString:DefaultConnection: "Server=petnews.database.windows.net;Database=blogpetnews;User Id=petnews;Password=7mxdWuSG5S-jz1);TrustServerCertificate=True;"
        ports:
            - "8080:80"
        networks:
            - blogpets-network
        depends_on:
            - petnewsdb

networks:
    blogpets-network:
        driver: bridge    

