version: '3.4'

services:
  petnewsdb:
    container_name: petnewsdb
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
        - "1433:1433"
    environment:
        - ACCEPT_EULA=Y
        - SA_PASSWORD=yLDLla@23X!lyDz
    networks:
        - blogpetnews
  blogpetnews.api:
    container_name: blogpetnews.api
    image: ${DOCKER_REGISTRY-}blogpetnewsapi
    build:
      context: .
      dockerfile: BlogPetNews.API/Dockerfile
    ports:
       - "5000:80"
    depends_on:
     - petnewsdb
    environment:
    - DB_HOST=petnewsdb
    - DB_NAME=BlogNewsDB
    - DB_SA_PASSWORD=yLDLla@23X!lyDz
    networks:
     - blogpetnews

networks:
  blogpetnews:
    name: blogpetnews
    
