version: '3'

services:
    blogpetnews:
        build: ./BlogPetNews.API
        image: rm348780.azurecr.io/techchallenge/blogpetnews
        container_name: blogpetnews
        # environment:
        #     - DefaultConnection=
        ports:
            - "8080:80"
        networks:
            - blogpets-network
        depends_on:
            - petnewsdb

    petnewsdb:
        image: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: ""
        ports:
            - "5432:5432"
        networks:
            - blogpets-network

networks:
    blogpets-network:
        driver: bridge    

